type: stats
reports:
  - label: Revenue
    value: €29,682
    info: +112.5%
    link: https://getkirby.com/buy
    theme: positive
  - label: Orders
    value: 265
    info: +82.8%
    theme: positive
  - label: Avg. Transaction
    value: €112.01
    info: +16.3%
    theme: positive
  - label: Refunds
    value: €15.20
    info: +10.5%
    theme: positive
  - label: Discount sales
    value: €1,422
    info: n/a
