title: Restaurant

options:
  title: false
  duplicate: false
  status: false
  url: false
  delete: false

buttons:
  - icon: calendar
    text: Open Table

columns:
  - width: 1/3
    sections:
      foo:
        type: fields
        fields:
          location:
            label: Map
            type: locator
      gallery:
        headline: Impressions
        type: files
        template: restaurant-gallery-image
        layout: cards
        size: small
        image:
          ratio: 4/3
          cover: true
  - width: 2/3
    sections:
      cover:
        type: files
        template: restaurant-cover-image
        layout: cards
        max: 1
        size: full
        image:
          ratio: 2/1
          cover: true
      fields:
        type: fields
        fields:
          starters:
            extends: fields/restaurant/dishes
            label: Starter
          meat:
            extends: fields/restaurant/dishes
            label: Main
          dessert:
            extends: fields/restaurant/dishes
            label: Dessert
