title: Site

tabs:
  overview:
    columns:
      - width: 1/2
        fields:
          fields: fields/fields
      - width: 1/2
        fields:
          other: fields/other
          benchmarks: fields/benchmarks
  content:
    label: Site Content
    fields:
      title:
        type: text
      text:
        type: textarea
  files:
    label: Site Files
    fields:
      files:
        type: filelist
