title: Site

tabs:
  overview:
    columns:
      - width: 1/2
        sections:
          fields: sections/fields
      - width: 1/2
        sections:
          sections: sections/sections
          other: sections/other
  content:
    label: Site Content
    fields:
      title:
        type: text
      text:
        type: textarea
  files:
    label: Site Files
    sections:
      files:
        type: files
